- R/utils.R
Closes #30 
This PR silences test warnings by following the warning advice: 
```r
i Please use `all_of(var)` (or `any_of(var)`) instead of `.data[[var]]`
```
For us this means replacing `.data[[col]]` with `any_of(col)`.
> In tests address warnings

- R/utils-test.R
- tests/testthat/_snaps/data.md
- tests/testthat/test-data.R
Closes #29 
This PR changes the way we store snapshots to make test-data.R run much faster -- from seemingly never finishing to running just over 1/2 second:
```
ℹ Testing tiltIndicatorAfter
✔ | F W S  OK | Context
✔ |        13 | data [0.6s]  
```
This opens the door to all other PRs, as there is little I can change confidently if I'm not able to run tests.
--
Also it makes the tests more robust to unimportant changes in the contents of the datasets, which are likely to change because we're still figuring out what the data should look like. 
Because we are in an early stage of development I believe it's best to sacrifice accuracy to gain development speed and maintainability.
> Minimize snapshots to make test-data.R run faster

- tests/testthat/test-prepare_istr_product.R
- tests/testthat/test-prepare_pstr_company.R
- tests/testthat/test-prepare_pstr_product.R
(Note "sector profile" is the new name for "pstr".)
In an earlier version of the package I see a test for the internal function `prepare_inter_pstr_product()`:
```r
test_that("risk_category colummn should not have more than one NA for no result companies", {
out <- prepare_inter_pstr_product(pstr_product, ep_companies, ecoinvent_activities, matches_mapper) |>
filter(is.na(risk_category)) |>
group_by(companies_id) |>
summarise(count = n())
expect_equal(unique(out$count), 1L)
})
```
This PR restores that test but via the public interface: `prepare_pstr_product()`. My inspection suggests that `prepare_pstr_product()` does nothing with `NA`s so they should be exactly as they were in the intermediate state created by the internal `prepare_inter_pstr_product()`.
Note I use a small version of …
> Test `*risk_category` in `sector_profile()` at product level

- tests/testthat/test-prepare_pstr_product.R
closes #72 
@AnneSchoenauer Only companies which have no risk category are assigned null `tilt_sector` and `tilt_subsector`. I have written a test which shows this behaviour.
> Test `tilt_sector` and `tilt_subsector` yield NAs for companies with no risk category

- R/prepare_ictr_company.R
- R/prepare_ictr_product.R
- R/prepare_istr_company.R
- R/prepare_istr_product.R
- R/prepare_pctr_company.R
- R/prepare_pctr_product.R
- R/prepare_pstr_company.R
- R/prepare_pstr_product.R
- R/rename.R
- README.Rmd
- README.md
- _pkgdown.yml
- man/prepare_ictr_company.Rd
- man/prepare_ictr_product.Rd
- man/prepare_istr_company.Rd
- man/prepare_istr_product.Rd
- man/prepare_pctr_company.Rd
- man/prepare_pctr_product.Rd
- man/prepare_pstr_company.Rd
- man/prepare_pstr_product.Rd
Replaces https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/93 because that one got too entangled
Closes https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/83
This PR deprecates the old API in favor of the new API. It follows the process documented [here](https://lifecycle.r-lib.org/articles/communicate.html#functions) except that I don't introduce a warning if the old API is called -- which is quite a bit of work because then we need to suppress the warning from each test that indirectly calls the old API. That work would be worth for a package that was used by external users, but so far I believe the users are all internal.
The signs of deprecation are:
* A badge in the helpfile.
* The removal of the examples and a redirection to examples in the new API.
* The …
> Deprecate the old API

- R/utils-test.R
- tests/testthat/test-prepare_ictr_company.R
- tests/testthat/test-prepare_pctr_company.R
Relates to https://github.com/2DegreesInvesting/tiltToyData/pull/17
This PR adapts tests to work with quoted values of `*isic*` -- which will be introduced soon via https://github.com/2DegreesInvesting/tiltToyData/pull/17. 
The affected tests may be obsolete and instead of handling numeric `*isic*` we should throw a warning or error -- see https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/102
> Adapt tests to new 'quoted' values of isic

- .github/workflows/R-CMD-check-tiltWorkflows.yaml
This PR adds a GitHub Actions workflow to avoid breaking tiltWorkflows. It checkout the PR from this repo, then runs R CMD check on tiltWorkflows.
> Avoid breaking tiltWorkflows

- R/select_datasets.R
Follow up https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/105#discussion_r1431848319
This PR picks distinct rows from `europages_companies` just like we do with `ecoinvent_inputs`.
> Pick distinct() rows from selected columns of europages_companies

- tests/testthat/helper.R
Relates to 2DegreesInvesting/tiltToyData#19
Relates to #122
This PR creates a local version of the deprecated `toy_emissions_profile*_products()`. This is to suppress the deprecation warning and reduce the noise during testing.
----
TODO
EXCEPTIONS
> Quiet deprecation warning from `toy_emissions_profile*_products()`

- tests/testthat/setup.R
Setup tests to read data quietly as documented in https://testthat.r-lib.org/articles/special-files.html#setup-files
The goal is to DRY the multiple instances when we use the option `readr.show_col_types = FALSE` -- i.e. to enable #133.
This is pure refactoring.
----
TODO
EXCEPTIONS
> Setup all tests to read data quietly

- R/prepare_ictr_product.R
- R/prepare_istr_product.R
- R/prepare_pctr_product.R
- R/prepare_pstr_product.R
- tests/testthat/_snaps/profile_emissions.md
- tests/testthat/_snaps/profile_sector_upstream.md
- tests/testthat/test-prepare_pctr_product.R
closes #138 
Dear @SKruthoff 
This PR removes the `extra_rowid` column from all the final output files. I am not implementing backward compatibility feature for this update because this column was of no use before as well.
@maurolepore I will correct the skipped unittest with other skipped tests after we will have the correct toy datasets of tiltIndicatorAfter. 
----
TODO
EXCEPTIONS
> Removes `extra_rowid` column

- R/prepare_ictr_product.R
- R/prepare_inter_pstr_product.R
- R/prepare_istr_product.R
- R/prepare_pctr_product.R
- R/prepare_pstr_product.R
- R/select_datasets.R
- tests/testthat/_snaps/profile_emissions.md
- tests/testthat/_snaps/profile_sector_upstream.md
- tests/testthat/test-profile_emissions.R
- tests/testthat/test-profile_emissions_upstream.R
- tests/testthat/test-profile_sector.R
- tests/testthat/test-profile_sector_upstream.R
closes #119 
This PR adds `ei_geography` column in `emission_profile` and `sector_profile` at product level, and adds both `ei_geography` and `ei_input_geography` in `emission_profile_upstream` and `sector_profile_upstream` at product level.
----
TODO
EXCEPTIONS
> Add `ei_geography` and `input_ei_geography` columns to product level outputs of all four profile indicators

- R/polish_emissions_profile_company.R
- R/polish_emissions_profile_upstream_company.R
- R/polish_sector_profile_company.R
- R/polish_sector_profile_upstream_company.R
- R/utils.R
- tests/testthat/_snaps/profile_emissions.md
- tests/testthat/_snaps/profile_sector_upstream.md
- tests/testthat/test-profile_emissions.R
- tests/testthat/test-profile_emissions_upstream.R
- tests/testthat/test-profile_sector.R
- tests/testthat/test-profile_sector_upstream.R
closes #161 
Dear @AnneSchoenauer @Tilmon @maurolepore,
This PR adds the `profile_ranking_avg` and `reduction_targets_avg` columns at company level in emission and sector profile indictors respectively. The average column is the mean of `profile_ranking` values after grouping the rows based on columns `companies_id` and `group_by`. You can look at a small example using this reprex:
```
library(readr)
library(dplyr)
devtools::load_all(".")
options(width = 500)
local_options(readr.show_col_types = FALSE)
companies <- read_csv(toy_emissions_profile_any_companies()) |>
filter(companies_id %in% c("nonphilosophical_llama"))
co2 <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities …
```
> Add `profile_ranking_avg` and `reduction_targets_avg` columns at company level in emission and sector profile indictors repectively

- R/utils.R
Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/164
This PR removes 228 warnings that clutter test results and obscure other important notifications.
cbd0ae40 introduced a deprecated usage of a tidyselect expression:
```
cbd0ae40 (Kalash Singhal 2024-02-27 07:46:07 +0100  93)     select(.data$companies_id, .data$grouped_by, .data$profile_ranking) |>
```
That yields 228 warnings:
```
══ Results ════════════════════════════════════════════════════════════════════════════════
Duration: 54.4 s
[ FAIL 0 | WARN 228 | SKIP 0 | PASS 79 ]
```
For example:
```
Warning (test-utils.R:61:3): rename_118() function is not applied if issue #118 is not addressed
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `"profile_ranking"` instead of …
```
> Remove warnings that clutter test results

- _pkgdown.yml
Relates to #160
This PR removes the needless section from the website's reference.
Before
----
TODO
EXCEPTIONS
> Remove an empty section from the website's Reference

- R/profile_emissions.R
- R/tiltIndicatorAfter-options.R
- R/utils-co2.R
- man/tiltIndicatorAfter_options.Rd
- tests/testthat/test-profile_emissions.R
Closes #185 
Extends #184
This PR focuses on the output of `profile_emissions()` at company level. It uses an option to allow licensed users to include the new column `co2_avg`  -- which is the mean of the licensed `co2_footprint` available at product level via the same option.
@AnneSchoenauer please see this reprex and confirm this is what you want.
<details/>
<summary/>
reprex
</summary>
``` r
library(withr)
devtools::load_all()
local_options(readr.show_col_types = FALSE)
companies <- read_csv(toy_emissions_profile_any_companies())
co2 <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- …
```
> At company level `profile_emissions()` can optionally output `co2_avg`

- R/prepare_inter_emissions_profile.R
- tests/testthat/test-profile_emissions.R
* Relates to #153 
In tiltIndicator "the `emissions*()` functions preserve unmatched products ([changelog](https://2degreesinvesting.github.io/tiltIndicator/news/index.html#tiltindicator-0009209)). I expected tiltIndicatorAfter to also preserve the "unmatched" products but instead it drops them:
<details/>
<summary/>
reprex
</summary>
``` r
library(tiltToyData)
library(tiltIndicator)
library(tiltIndicatorAfter)
withr::local_options(readr.show_col_types = FALSE)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9211'
packageVersion("tiltIndicatorAfter")
#> [1] '0.0.0.9023'
companies <- read_csv(toy_emissions_profile_any_companies())
id <- unique(companies$companies_id)[[1]]
uuid <- …
```
> `profile_emissions()` now preserves unmatched products

- R/profile_emissions_upstream.R
- man/profile_emissions_upstream.Rd
This PR fixes the formatting of a sentence in the docs. It's a minor thing but is a small change so I'll fix it while I'm here.
The cause is unclear though. It seems that code-formatting (back ticks) right at the end of a line are confused with a line break.
https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html#value
----
TODO
EXCEPTIONS
> Fix formatting in one sentence of the docs

- R/exclude_cols_then_pivot_wider.R
- man/exclude_cols_then_pivot_wider.Rd
- tests/testthat/_snaps/exclude_cols_then_pivot_wider.md
- tests/testthat/test-exclude_cols_then_pivot_wider.R
Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/205#discussion_r1555755033. 
Thanks @kalashsinghal 
`exclude_cols_then_pivot_wider()` now allows avoiding list-columns via the new argument `avoid_list_cols`. 
This is a coarse, catch-all alternative to the finer grained control you get via `id_cols`. While it's generally best to specify the `id_cols` you care about, it's hard to anticipate what columns the real data might have, and some of them may introduce list-columns, duplicates, and trigger a warning. This new argument avoids all of that.
<details/>
<summary/>
reprex
</summary>
``` r
devtools::load_all()
library(tidyr, warn.conflicts = FALSE)
data <- tribble(
~id, ~name, ~value, ~to_exclude, …
```
> `exclude_cols_then_pivot_wider()` gains `avoid_list_cols`

- R/utils-co2.R
- tests/testthat/_snaps/profile_emissions.md
- tests/testthat/test-profile_emissions.R
Closes #188 
This PR removes `NA`s when `inform_percent_noise()` computes the mean noise. The reprex shows that the message matches the calculated values:
<details/>
<summary/>
reprex
</summary>
``` r
devtools::load_all()
withr::local_options(readr.show_col_types = FALSE)
withr::local_options(tiltIndicatorAfter.output_co2_footprint_min_max = TRUE)
withr::local_options(tiltIndicatorAfter.output_co2_footprint = TRUE)
withr::local_seed(1)
companies <- read_csv(toy_emissions_profile_any_companies(), n_max = 1)
companies <- bind_rows(companies, companies)
companies$activity_uuid_product_uuid[[1]] <- "unmatched"
uuid <- unique(companies$activity_uuid_product_uuid)
products <- …
```
> `inform_percent_noise()` now yields correct noise, not "NA% and NA%"

- R/tiltIndicatorAfter-options.R
- R/utils-co2.R
This PR is refactoring only. It gives more evocative and consistent names 
to the functions that get options.
These changes moved from #214, in order to reduce the diff of that PR.
----
TODO
EXCEPTIONS
> Refactor: Rename internal `option_*()` helpers

- tests/testthat/test-profile_emissions.R
* Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/214#discussion_r1587334496
>  This test is testing that if `*profile$` column has NA then `tilt_sector` and `tilt_subsector` should always have NA. If you think this test is incompatible with this PR, then please remove it! -- @kalashsinghal 
This PR aims to rewrite a test in such a way that remains true to its original intent, while being compatible with a future change comming in #214 
@kalashsinghal please review to ensure I interpreted your intent correctly.
The arrangement of the test-data is hard to understand, but if you run the test interactively you'll see that all it does is to create a `companies` dataset that has an "unmatched" product, so the result at product level has an `NA` in `emission_profile`. If …
> Refactor: Rewrite test

- NEWS.md
- tests/testthat/test-profile_emissions.R
* Relates to #231 
This PR completes the story of #231. It adds an entry in the changelog that explains a user-facing change I forgot to mention, and adds tests that clarify the distinction between columns in the output at product versus company level.
This doesn't touch production code. I'll go ahead without review.
----
TODO
EXCEPTIONS
> Refactor: Add info to the changelog and tests about #231

- .github/pull_request_template.md
Relates to https://github.com/2DegreesInvesting/tiltPlot/pull/132#pullrequestreview-2069382782 (see my reasons there).
I edit the changelog with [fledge](https://fledge.cynkra.com/) but it's also easy to do manually:
- Edit NEWS.md
- Increment the version number in DESCRIPTION
- Tag the commit with the new version with something like:
```bash
git tag -a <version> -m "Some message"
git push origin <version>
```
----
TODO
EXCEPTIONS
> Update pr checklist to remind ourselves to document user-facing changes

- R/best_case_worst_case_emission_profile.R
- R/best_case_worst_case_impl.R
- R/cols-best_case_worst_case.R
- R/utils-best_case_worst_case.R
- man/transition_risk_profile.Rd
- tests/testthat/test-best_case_worst_case_emission_profile.R
Relates to #248 
Dear @maurolepore 
As we now want to implement `best case and worst case` methodology to transition risk indicator, we need to refactor the current code so that the duplication can be removed and we can use the existing code to calculate the best case and worst case for other indicators. 
Please review the refactoring! Thanks!
cc @Tilmon 
----
TODO
> Refactor `best_case_worst_case_emission_profile` function 

- R/best_case_worst_case.R
- R/polish_best_case_worst_case.R
- R/transition_risk_profile.R
Relates to #248 
This PR removes unnecessary best case and worst case columns for `transition risk profile`
----
TODO
> Remove unnecessary best case and worst case columns for `transition risk profile`

- R/utils-best_case_worst_case.R
Merges into `257_avg_transition_risk_best_case_worst_case`
This PR fixes many warnings I see when I run `devtools::test().
--
RE https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/269#issuecomment-2186208871
When you run `devtools::test()` you get 0 errors, 0 warnings, 0 notes?
Not sure why but you may try in a fresh envorinment. Maybe try posit.cloud, GitHub codespaces, or Docker.
But you can also reproduce the warning in a reprex. 
``` r
good <- function(data) {
col <- "cyl"
mutate(data, x = cyl, .by = all_of(col))
}
bad <- function(data) {
col <- "cyl"
mutate(data, x = cyl, .by = col)
}
data <- mtcars[1:3, 1:3]
data |> good()
#>                mpg cyl disp x
#> Mazda RX4     21.0   6  160 6
#> Mazda RX4 Wag 21.0   6  160 6
#> Datsun 710 …
```
> Fix test warnings

- R/score_transition_risk.R
- tests/testthat/test-score_transition_risk.R
closes #262 
Dear @maurolepore,
This PR limits the transition risk scores between 0 and 1. Please review! Thanks!
----
TODO
> Add function `limit_transition_risk_score_between_0_and_1()`

- R/pivot_wider_transition_risk_profile.R
- R/score_transition_risk_and_polish.R
- R/transition_risk_profile.R
- man/pivot_wider_transition_risk_profile.Rd
- man/score_transition_risk_and_polish.Rd
- tests/testthat/test-score_transition_risk_and_polish.R
- tests/testthat/test-transition_risk_profile.R
closes [issue](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/187)
Dear @AnneSchoenauer @Tilmon @maurolepore,
According to the old code, we can't output `co2_footprint` and `co2_avg` from `transition_risk_profile` if other columns are converted into wide format. After discussion with @AnneSchoenauer, we came to the conclusion that co2 columns should be visible in the output tables irrespective of other columns' wide format. Therefore, this PR removes the dependency of co2 columns on wider format option and also ensures that we can choose whether we want the co2 columns in the final output using the `*.output_co2_footprint` option. 
You can also check the same using below reprex:
``` r …
```
> `transition_risk_profile` outputs `co2_footprint` at product level and `co2_avg` at company level if `*.output_co2_footprint = TRUE`

- R/pivot_wider_transition_risk_profile.R
- R/score_transition_risk_and_polish.R
- tests/testthat/test-transition_risk_profile.R
Relates to [issue](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/189)
According to the [excel sheet](https://docs.google.com/spreadsheets/d/1e5QUcHBb6m9AcgHEK59RrFaTC69-MZ-t/edit?gid=424568592#gid=424568592), there are some columns which are still needed to be added at product and company level. This PR adds these columns.
----
TODO
> Add remaining columns at product and company level for `transition_risk_profile()` indicator 

- R/relocate_transition_risk_profile_cols.R
- R/transition_risk_profile.R
Relates to [issue](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/189)
This PR adds new function `relocate_transition_risk_profile_cols()` to relocate the transition risk profile columns as given in this [excel sheet](https://docs.google.com/spreadsheets/d/1e5QUcHBb6m9AcgHEK59RrFaTC69-MZ-t/edit?gid=424568592#gid=424568592).
----
TODO
> Add function `relocate_transition_risk_profile_cols()` to relocate output columns of transition risk profile

- R/best_case_worst_case_impl.R
- R/utils-best_case_worst_case.R
- tests/testthat/test-best_case_worst_case_emission_profile.R
- tests/testthat/test-best_case_worst_case_transition_risk_profile.R
closes #285 
Dear @AnneSchoenauer @Tilmon 
Here is the reprex to show that this PR covers all the cases outlined in the [comment](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/285#issuecomment-2225066904):
``` r
library(tiltToyData, warn.conflicts = FALSE)
library(tiltTransitionRisk, warn.conflicts = FALSE)
devtools::load_all(".")
options(width = 5000)
example_data <- example_best_case_worst_case_transition_risk_profile(
companies_id = c("any", "any", "any", "any", "any", "any", "any"),
ep_product = c("one", "two", "three", "one", "two", "three", "four"),
benchmark_tr_score = c("all", "all", "all", "tilt_sector", "tilt_sector", "tilt_sector", NA_character_), …
```
> Make `equal_weight` consistent with `best_case` and `worst_case` by not considering NAs

- R/best_case_worst_case_avg_profile_ranking.R
- R/best_case_worst_case_avg_reduction_targets.R
- R/best_case_worst_case_impl.R
- R/best_case_worst_case_transition_risk_profile_at_company_level.R
- R/pivot_wider_transition_risk_profile.R
- R/polish_best_case_worst_case.R
- R/relocate_transition_risk_profile_cols.R
- R/score_transition_risk.R
- R/score_transition_risk_and_polish.R
- R/transition_risk_profile.R
- R/utils-best_case_worst_case.R
- tests/testthat/_snaps/profile_emissions.md
- tests/testthat/test-transition_risk_profile.R
Dear @Tilmon,
This PR adds the `amount_of_distinct_products_matched` column at product level for both emissions profile and transition risk profile to better understand the updated `equal_weight` column which uses `amount_of_distinct_products_matched` instead of `amount_of_distinct_products` (old input).
This PR also removes warnings after including `all_of()` function.
----
TODO
> Adds column `amount_of_distinct_products_matched` at product level for both emissions profile and transition risk profile 

- R/add_transition_risk_NA_share.R
- R/relocate_transition_risk_profile_cols.R
- R/transition_risk_profile.R
- tests/testthat/test-transition_risk_profile.R
closes #289
Dear @maurolepore,
This PR creates the `add_transition_risk_NA_share()` function to add column `transition_risk_NA_share` at product and company level for transition risk profile. It also adds `transition_risk_NA_total` column at product level.
Theoretical review is already done by @Tilmon using real data. Hence, @maurolepore I would like your technical review on this PR. Thanks!
----
TODO
> Create `add_transition_risk_NA_share()` function for transition risk profile indicator

- R/coefficient_of_variation_transition_risk_profile.R
- tests/testthat/test-coefficient_of_variation.R
closes #304
This PR fixes the coefficient of variation by assigning NA to it if the mean is zero too ([issue](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/304)). As you can see from the below reprex, the `cov_sector_target` is NA if `mean_sector_target` is zero.
``` r
library(tibble, warn.conflicts = FALSE)
devtools::load_all(".")
options(width = 5000)
sector_target_input <- tibble(
reduction_targets_avg = -1,
avg_reduction_targets_best_case = 1,
avg_reduction_targets_worst_case = 0
)
out <- tiltIndicatorAfter:::add_coefficient_of_variation_sector_target(sector_target_input)
out
#> # A tibble: 1 × 6
#>   reduction_targets_avg avg_reduction_targets_best_case avg_reduction_targets_worst_case mean_sector_target …
```
> Assign NA to `coefficient_of_variation` if mean is zero

- R/prepare_webtool_output.R
- R/transition_risk_profile.R
- tests/testthat/test-transition_risk_profile.R
* closes https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/197
* Relates to https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/209
This PR removes the Case 3 companies followed by this [comment](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/169#issuecomment-2284344632) from the base output of `tiltIndicatorAfter`. It also removes the `co2_footprint` column at product level and `co2e_avg` column at company level for webtool output.
----
TODO
> Remove case 3 companies for the base output and co2 columns for the webtool output

- DESCRIPTION
- R/pivot_wider_transition_risk_profile.R
- R/prepare_webtool_output.R
- R/relocate_transition_risk_profile_cols.R
- R/transition_risk_profile.R
- man/pivot_wider_transition_risk_profile.Rd
- man/tiltIndicatorAfter-package.Rd
- man/transition_risk_profile.Rd
- tests/testthat/test-transition_risk_profile.R
* closes #301 
Dear,
This PR removes the `long-format` and keep only the `wide-format` option for the company-level output columns. It's an old requirement which will be deleted, and hence no testing is required. 
----
TODO
> Remove long format option for company level columns
