R/prepare_ictr_company.R
R/prepare_ictr_product.R
R/prepare_inter_pctr_product.R
R/prepare_inter_pstr_product.R
R/prepare_istr_company.R
R/prepare_istr_product.R
R/prepare_matches_mapper.R
R/prepare_pctr_company.R
R/prepare_pctr_product.R
R/prepare_pstr_company.R
R/prepare_pstr_product.R
README.Rmd
tests/testthat/test-prepare_ictr_company.R
tests/testthat/test-prepare_inter_pstr_product.R
tests/testthat/test-prepare_pctr_company.R

Refactoring and styling for complete package

Refactor and style

---

R/prepare_ictr_product.R
R/prepare_inter_pctr_product.R
R/prepare_inter_pstr_product.R
R/prepare_istr_product.R
R/prepare_pctr_product.R
R/utils.R

Refactor code

---

.github/workflows/check-standard.yaml

Add workflow file

---

R/prepare_ictr_product.R
R/prepare_istr_company.R
R/tiltIndicatorAfter_runner_ictr.R
R/tiltIndicatorAfter_runner_istr.R
R/tiltIndicatorAfter_runner_pctr.R
R/tiltIndicatorAfter_runner_pstr.R
README.md

update r scripts

---

R/prepare_istr_product.R

Remove columns from ISTR product level results

remove columns

---

R/tiltIndicatorAfter_runner_istr.R
R/tiltIndicatorAfter_runner_pstr.R

update runner scripts

---

R/prepare_ictr_company.R
R/prepare_ictr_product.R
R/prepare_inter_pctr_product.R
R/prepare_inter_pstr_product.R
R/prepare_istr_company.R
R/prepare_istr_product.R
R/prepare_pctr_company.R
R/prepare_pctr_product.R
R/prepare_pstr_company.R
R/utils.R

Add meta data to final outputs

---

tests/testthat/test-prepare_ictr_company.R
tests/testthat/test-prepare_ictr_product.R
tests/testthat/test-prepare_istr_company.R
tests/testthat/test-prepare_istr_product.R
tests/testthat/test-prepare_pctr_company.R
tests/testthat/test-prepare_pctr_product.R
tests/testthat/test-prepare_pstr_company.R
tests/testthat/test-prepare_pstr_product.R

Add tests for all indicators

---

inst/extdata/tiltIndicatorAfter_runner_pctr.Rmd

tiltIndicatorAfter_runner_pctr.Rmd file

Add Runner .Rmd file

---

R/prepare_inter_pctr_product.R
R/prepare_pctr_product.R
R/prepare_pstr_product.R
R/utils.R

Closes #41 
This is a pretty simple fix, and all functions are covered by tests, so I'll merge without review.

Return visibly

---

README.Rmd
README.md

This is to minimize the exposure of names that will soon change

Minimize README

---

R/profile_emissions.R
R/profile_emissions_upstream.R
R/profile_sector.R
R/profile_sector_upstream.R
R/select_datasets.R
man/tiltIndicatorAfter-package.Rd
tests/testthat/_snaps/profile_emissions.md
tests/testthat/_snaps/profile_sector_upstream.md
tests/testthat/test-profile_emissions.R
tests/testthat/test-profile_emissions_upstream.R
tests/testthat/test-profile_sector.R
tests/testthat/test-profile_sector_upstream.R

Exclude irrelevant columns from `europages_companies` and `ecoinvent_inputs`

---

R/utils.R
tests/testthat/test-prepare_ictr_company.R
tests/testthat/test-prepare_pctr_product.R
tests/testthat/test-prepare_pstr_product.R

This PR is generated automatically with `usethis::use_tidy_style()`.

Run an automated code styler

---

.github/pull_request_template.md

This PR adds a checklist on each PR as we do in other tilt packages. 
I've found this is of great help, particularly when I work alone. It
helps me catch little problems quickly before they coumpound to a more
expensive problem to solve.

Add a checklist for each PR

---

DESCRIPTION
LICENSE.md

Closes #139
----
TODO
EXCEPTIONS

Use license GPLv3

---

R/profile_emissions_upstream.R
R/score_transition_risk.R
man/profile_emissions_upstream.Rd
man/score_transition_risk.Rd
tests/testthat/test-profile_emissions.R
tests/testthat/test-profile_emissions_upstream.R

Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/163
This PR extracts changes in #163 that are not directly related to the intent of #163. Merging this into `main` before #163 will leave #163 more focused, making it easier to understand and review.
----
TODO
EXCEPTIONS

Use `*products_ecoinvent()`

---

R/profile_emissions_upstream.R
R/profile_sector_upstream.R

This PR swaps the location of the helpfile source. This refactoring anticipates a change that needs to extend the return value of the `emissions*()` but not the `sector*()`.
----
TODO
EXCEPTIONS

Swap location of helpfile soruce

---

R/profile_emissions_upstream.R
man/profile_emissions_upstream.Rd

Relates to #155 
This PR documents the new `co2*` columns.
Thanks @Tilmon 
https://2investinginitiative.slack.com/archives/C04RFVACX28/p1709125270345529
----
TODO
EXCEPTIONS

Document the `co2*` columns

---

R/tiltIndicatorAfter-options.R
R/utils-co2.R
man/tiltIndicatorAfter_options.Rd
tests/testthat/test-profile_emissions.R
tests/testthat/test-profile_emissions_upstream.R

Rename options to be more evocative and consistent

---

tests/testthat/test-profile_emissions.R

Relates to:
* #153
* #196
Extends:
* #193
This PR extracts a test from an irrelevant PR (#196) to avoid [confusion](https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/196#issuecomment-2012461883). It doesn't touch any production code and enhances the code base by adding a new test.
<details/>
<summary/>
reprex
</summary>
``` r
library(tiltToyData)
library(tiltIndicator)
devtools::load_all()
withr::local_options(
width = 500,
readr.show_col_types = FALSE
)
companies <- read_csv(toy_emissions_profile_any_companies())
id <- unique(companies$companies_id)[[1]]
uuid <- unique(companies$activity_uuid_product_uuid)[[1]]
companies <- companies |>
filter(companies_id == id) |> …
```

With some match also preserves unmatched products

---

tests/testthat/test-profile_emissions.R

closes #72 
This PR adds similar test present in Sector profile indicator to the Emissions profile indicator. 
----
TODO
EXCEPTIONS

Test `tilt_sector` and `tilt_subsector` yield NAs if `emission_profile` column has NA for Emissions profile indicator

---

R/score_transition_risk.R
R/utils-score_transition_risk.R

Relates to #182 
Rename `benchmark_tr_score` to `benchmark_tr_score_avg` after Anne's comment [here](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/182#issuecomment-1986775045).
----
TODO
EXCEPTIONS

Rename `benchmark_tr_score` to `benchmark_tr_score_avg`

---

tests/testthat/test-score_transition_risk.R

Follows up #199 
This PR tests the new column. This gives me the confidence I need to document this breaking change in NEWS.md.
----
TODO
EXCEPTIONS

Test the new column `benchmark_tr_score_avg`

---

R/utils-co2.R

* Relates to 2DegreesInvesting/tiltIndicator#764
This is pure refactoring -- to allow introducing a change in tiltIndicator without breaking code here.
I'll go ahead and merge.
----
TODO
EXCEPTIONS

Refactor: Prepare for tiltIndicator#764

---

R/utils-co2.R

* Relates to #216 
This PR refines the previous PR by suppressing only a specific warning rather than all warnings. It's pure refactoring.
----
TODO
EXCEPTIONS

Refactor: Refine warning class

---

R/profile_emissions_upstream.R
R/profile_impl.R
R/profile_sector_upstream.R
man/profile_emissions_upstream.Rd
man/profile_impl.Rd
man/profile_sector_upstream.Rd

This PR helps developers find the topic `profile_impl` by linking to it from the
top-level functions. Then it's easy to follow links to other composable friends.
This doesn't affect production code -- only documentation.
----
TODO
EXCEPTIONS

Link to `?profile_impl` from top-level functions

---

tests/testthat/test-profile_emissions.R

This is a tiny refactoring that removes a needless, empty call to `withr::local_options()`. The goal is to cleanup as I go.
----
TODO
EXCEPTIONS

Refactor: Prune dead code

---

tests/testthat/test-profile_emissions_upstream.R

* Relates to #230 
* Relates to #232 
Same as #232 but for `*upstream()` (which I missed before).
----
TODO
EXCEPTIONS

Refactor: Prepare for #230

---

R/pivot_wider_transition_risk_profile.R
R/score_transition_risk_and_polish.R

Resolve small bug

---

R/coefficient_of_variation_transition_risk_profile.R
tests/testthat/test-coefficient_of_variation.R

close #304 
This PR fixes the coefficient of variation by assigning zero to it if the mean is zero too ([issue](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/304)). As you can see from the below reprex, the `cov_sector_target` is zero if `mean_sector_target` is zero.
``` r
library(tibble, warn.conflicts = FALSE)
devtools::load_all(".")
options(width = 5000)
sector_target_input <- tibble(
reduction_targets_avg = -1,
avg_reduction_targets_best_case = 1,
avg_reduction_targets_worst_case = 0
)
out <- tiltIndicatorAfter:::add_coefficient_of_variation_sector_target(sector_target_input)
out
#> # A tibble: 1 × 6
#>   reduction_targets_avg avg_reduction_targets_best_case avg_reduction_targets_worst_case mean_sector_target …
```

Assign zero to `coefficient_of_variation` if mean is zero

---

DESCRIPTION
vignettes/articles/tilt_input_analysis.Rmd

Relates to #309 
This PR adds the article for basic documentation of "Input and Supply Chain Analysis Model".
----
TODO

Add article for "Input and Supply Chain Analysis Model"

---

vignettes/articles/tilt_input_analysis.Rmd

Rephrase article "Input and Supply Chain Analysis Model".
